---
title: "project"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false
library(httr2)
url <- "https://api.census.gov/data/2021/pep/population"
request <- 
  request(url) |>
  req_url_query(get = I("POP_2020,POP_2021,NAME"), 
                `for` = I("state:*"), 
                key = "3a47627720cc68b5f667bae037b7f8bf8add9eb9")

response <- request |> req_perform()
population <- resp_body_json(response, simplifyVector = TRUE)
library(tidyverse)
library(janitor)
population <- population |> 
  janitor::row_to_names(1) |>
  as_tibble() |>
  select(-state) |>
  rename(state_name = NAME) |>
  pivot_longer(-state_name, names_to = "year", values_to = "population") |>
  mutate(year = str_remove(year, "POP_")) |>
  mutate(across(-state_name, as.numeric)) |>
  mutate(state = state.abb[match(state_name, state.name)]) |>
  mutate(state = case_when(state_name == "District of Columbia" ~ "DC",
                           state_name == "Puerto Rico" ~ "PR",
                           .default = state))
```

```{r}
api <- "https://data.cdc.gov/resource/pwn4-m3yp.json"
cases_raw <- request(api) |>
  req_url_query("$limit" = 10000000) |>
  req_perform() |>
  resp_body_json(simplifyVector = TRUE)

cases <- cases_raw |>
  mutate(cases = parse_number(new_cases),
         date = as_date(ymd_hms(end_date))) |>
  filter(state %in% population$state) |>
  select(state, date, cases) |>
  arrange(state, date) 

cases <- cases |>
  mutate(year = year(date)) |>
  left_join(population, by = c("state","year"))
```


```{r}
cases |> 
  group_by(date) |> 
  summarize(
    total_cases = sum(cases, na.rm = TRUE),
    total_population = sum(population, na.rm = TRUE)
  ) |> 
  mutate(cases_per_100k = (total_cases / total_population) * 100000) |> 
  ggplot(aes(x = date, y = cases_per_100k)) +
  geom_line(color = "blue") +
  labs(
    title = "Cases per 100,000 People Over Time",
    x = "Date",
    y = "Cases per 100,000")
```

The `echo: false` option disables the printing of code (only output is displayed).
